typography_spectrum: 0.1411
color:
  brandColors:
    - '#010001'
    - '#ceb049'
    - '#55420e'
    - '#816822'
    - '#e3d67d'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.10926
analytics:
  google: null
  facebook: null
  twitter: null
name: Château Lestevenie
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Wine
description: here
purpose: []
