name: Château Lestevenie
favicon: null
layout_spectrum: 0.87506
typography_spectrum: 0.1411
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010001'
    - '#ceb049'
    - '#55420e'
    - '#816822'
    - '#e3d67d'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
